apiVersion: v1
kind: Service
metadata:
  name: visit-counter
  labels:
    app: visit-counter
spec:
  type: NodePort
  selector:
    app: visit-counter
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
    protocol: TCP

